### ISSUE TITLE
Solving parsing tests

### ISSUE THREAD

**Issue by LeCalicot** [juniperparsnips/rink-runtime#7]
The problem with the parsing tests is linked to [this line](https://github.com/juniperparsnips/rink-runtime/blob/7f0bdeeabc8e7985b3f65ca6f7e30e48a42d6923/src/parser/mod.rs#L633C45-L633C45).

The deserializer expects to deserialize a map but what we give in the tests are lists. Therefore serde cannot deserialize to a map. Moreover, the list is not implemented yet!

There is the question whether a list can ever be a valid ink runtime...I don't think so?

**Comment by IFcoltransG** [comment]
Solved in #8 (except for #10, which is the nested subcontainer test).

**Comment by juniperparsnips** [comment]
> Solved in #8 (except for #10, which is the nested subcontainer test).

I'll close this issue then since #10 is more specific.
